### ISSUE TITLE
Error after upgrading to .NET 3.1

### ISSUE THREAD

**Issue by rschiefer** [OData/Extensions#42]
Connection id "0HM1US5IK9AH0", Request id "0HM1US5IK9AH0:00000002": An unhandled exception was thrown by the application.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.AggregateException: One or more errors occurred. (Method 'get_Timeout' in type 'Microsoft.OData.Extensions.Client.HttpClientRequestMessage' from assembly 'Microsoft.OData.Extensions.Client, Version=1.0.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.)
 ---> System.TypeLoadException: Method 'get_Timeout' in type 'Microsoft.OData.Extensions.Client.HttpClientRequestMessage' from assembly 'Microsoft.OData.Extensions.Client, Version=1.0.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
   at Microsoft.OData.Extensions.Client.HttpClientODataClientHandler.<>c__DisplayClass4_0.<OnClientCreated>b__0(DataServiceClientRequestMessageArgs args)
   at Microsoft.OData.Client.RequestInfo.CreateRequestMessage(BuildingRequestEventArgs requestMessageArgs)
   at Microsoft.OData.Client.ODataRequestMessageWrapper.CreateRequestMessageWrapper(BuildingRequestEventArgs requestMessageArgs, RequestInfo requestInfo)
   at Microsoft.OData.Client.ODataMessageWritingHelper.CreateRequestMessage(BuildingRequestEventArgs requestMessageArgs)
   at Microsoft.OData.Client.DataServiceRequest.CreateExecuteResult(Object source, DataServiceContext context, AsyncCallback callback, Object state, String method)
   at Microsoft.OData.Client.DataServiceRequest.BeginExecute(Object source, DataServiceContext context, AsyncCallback callback, Object state, String method)
   at Microsoft.OData.Client.DataServiceQuery`1.BeginExecute(AsyncCallback callback, Object state)
   at Microsoft.OData.Client.DataServiceQuery`1.BeginExecuteInternal(AsyncCallback callback, Object state)
   at Microsoft.OData.Client.DataServiceQuery.BeginExecute(AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory`1.FromAsync(Func`3 beginMethod, Func`2 endMethod, Object state)
   at Microsoft.OData.Client.DataServiceQuery.ExecuteAsync()
   at SutureHealth.Shared.OData.ODataExtensions.ToListAsync[T](IQueryable`1 queryable)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)

**Comment by UM001** [comment]
I reverted again back to 7.6.4 version and not using 7.0.0. I am on .net core 3.1 as well.
That fixes it for me + has some issues in 7.6.4. I think the extension is not updated to work with latest 7.0.0 or timeout has no interface to protect that implementation of Timeout is forgotten. Last change on 7.0.0 indicate that there have been some changes by @ElizabethOkerio
